import { Inter } from 'next/font/google'
import './globals.css'
// import Script from 'next/script'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


// export function MyApp({ Component, pageProps }) {
//   return (
//     <>
//       <Component {...pageProps} />
//       <Script src="https://product-gallery.cloudinary.com/all.js" type="text/javascript" />
//     </>
//   )
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <script src="https://product-gallery.cloudinary.com/all.js" type="text/javascript">
        </script>
      </body>
    </html>
  )
}
